version: '3.1'

services:
  db:
    image: mysql
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: golang
      MYSQL_PASSWORD: badpassword
    ports:
        - 3307:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080


